title: Suhana Saffar
author: Uplabdhee
email: avnigungun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I don't know if I will win, I may not. Yet, I will try. When you try, you have won the battle halfway!

# social links
twitter_username: uplabdhee # DO NOT include the @ character, or else the build will fail!
github_username:  KaizenGirl111 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
